#!/bin/bash

echo "🚀 Over The Hill - Environment Setup"
echo "======================================"
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists."
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

# Copy template if it doesn't exist
if [ ! -f ".env.local" ]; then
    cp .env.example .env.local
    echo "✅ Created .env.local from template"
fi

echo ""
echo "📋 You need to configure your Supabase credentials:"
echo ""
echo "1. Go to https://supabase.com/dashboard"
echo "2. Select your project (or create a new one)"
echo "3. Go to Settings > API"
echo "4. Copy the following values:"
echo ""
echo "   📍 Project URL (looks like: https://abcdefg.supabase.co)"
echo "   🔑 Anon/Public Key (starts with: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...)"
echo "   🔐 Service Role Key (starts with: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...)"
echo ""

# Interactive setup
read -p "Enter your Supabase Project URL: " supabase_url
read -p "Enter your Supabase Anon Key: " supabase_anon_key
read -p "Enter your Supabase Service Role Key: " supabase_service_key

# Validate inputs
if [ -z "$supabase_url" ] || [ -z "$supabase_anon_key" ]; then
    echo "❌ Error: Project URL and Anon Key are required!"
    echo "Please run this script again with the correct values."
    exit 1
fi

# Update .env.local file
cat > .env.local << EOF
# Supabase Configuration
# Generated by setup-env.sh on $(date)

# Your Supabase project URL
NEXT_PUBLIC_SUPABASE_URL=$supabase_url

# Your Supabase anon/public key
NEXT_PUBLIC_SUPABASE_ANON_KEY=$supabase_anon_key

# Your Supabase service role key (for server-side operations)
# This key has admin privileges, keep it secure and never expose it to the client
SUPABASE_SERVICE_ROLE_KEY=$supabase_service_key
EOF

echo ""
echo "✅ Environment variables configured successfully!"
echo ""
echo "🔧 Next steps:"
echo "1. Restart your development server:"
echo "   npm run dev"
echo "   # or"
echo "   pnpm dev"
echo ""
echo "2. Your app should now connect to Supabase properly"
echo ""
echo "🔒 Security reminder:"
echo "- Never commit .env.local to version control"
echo "- Keep your service role key secure"
echo "- The anon key is safe to use in client-side code"
echo ""

# Check if development server is running
if pgrep -f "next dev" > /dev/null; then
    echo "⚠️  Development server is still running."
    echo "Please restart it to load the new environment variables:"
    echo "1. Stop the server (Ctrl+C)"
    echo "2. Run: npm run dev (or pnpm dev)"
fi