baseURL = 'https://gfaurobert.github.io/over-the-hill/'
languageCode = 'en-us'
title = 'Over The Hill - Documentation'
description = 'A web and desktop application designed to visualize project progress using Hill Charts'

[params]
  author = "gfaurobert"
  github = "https://github.com/gfaurobert/over-the-hill"

